security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\CustomerUser: 'auto'
        App\Entity\SystemUser: 'auto'
    
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        customer_users:
            entity:
                class: App\Entity\CustomerUser
                property: email
        system_users:
            entity:
                class: App\Entity\SystemUser
                property: email
        # Chain provider to try both user types
        chain_provider:
            chain:
                providers: ['customer_users', 'system_users']
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Customer API endpoints
        customer_api:
            pattern: ^/api/v1/customer
            stateless: true
            provider: customer_users
            json_login:
                check_path: /api/v1/customer/login
                username_path: email
                password_path: password
                success_handler: App\Security\CustomerAuthenticationSuccessHandler
                failure_handler: App\Security\AuthenticationFailureHandler
            jwt: true
        
        # System/Admin API endpoints  
        system_api:
            pattern: ^/api/v1/system
            stateless: true
            provider: system_users
            json_login:
                check_path: /api/v1/system/login
                username_path: email
                password_path: password
                success_handler: App\Security\SystemAuthenticationSuccessHandler
                failure_handler: App\Security\AuthenticationFailureHandler
            jwt: true
        
        # Public API endpoints (registration, etc.)
        public_api:
            pattern: ^/api/v1
            stateless: true
            security: false
            
        # Admin web interface
        admin_firewall:
            pattern: ^/admin
            lazy: true
            provider: system_users
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
                enable_csrf: false
            logout:
                path: admin_logout
                target: admin_login
                
        # Customer web interface  
        customer_firewall:
            pattern: ^/customer
            lazy: true
            provider: customer_users
            form_login:
                login_path: customer_login
                check_path: customer_login
                default_target_path: /customer/dashboard
                always_use_default_target_path: true
                enable_csrf: true
            logout:
                path: customer_logout
                target: customer_login
        
        # Default firewall for web interface (MUST be last)
        main:
            lazy: true
            provider: chain_provider
            form_login:
                login_path: app_login_new
                check_path: app_login_new
                default_target_path: /dashboard
                always_use_default_target_path: false
                enable_csrf: false
            logout:
                path: logout
                target: app_login_web

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Customer API routes
        - { path: ^/api/v1/customer/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/customer, roles: ROLE_CUSTOMER_USER }
        
        # System API routes
        - { path: ^/api/v1/system/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/system, roles: ROLE_SYSTEM_USER }
        
        # Admin web routes
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_SYSTEM_USER }
        
        # Customer web routes
        - { path: ^/customer/login, roles: PUBLIC_ACCESS }
        - { path: ^/customer, roles: ROLE_CUSTOMER_USER }
        
        # Dashboard routes - require authentication
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        
        # Public access
        - { path: ^/api/v1/registration, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
