# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # InPost API Client
    App\Service\InPostApiClient:
        autowire: false
        arguments:
            - '@http_client'
            - '%env(INPOST_API_URL)%'
            - '%env(INPOST_TOKEN)%'
            - '%env(INPOST_ORGANIZATION_ID)%'

    # Security Services
    App\Security\SecurityLogger:
        arguments:
            - '@monolog.logger'
        tags:
            - { name: monolog.logger, channel: security }
    
    App\Security\InputValidator:
        arguments:
            - '@validator'
    
    App\Security\RateLimiter:
        arguments:
            - '@cache.app'
            - '@logger'
            - '@App\Security\SecurityLogger'
    
    App\Security\JWTManager:
        arguments:
            - '@lexik_jwt_authentication.jwt_manager'
            - '@doctrine.orm.entity_manager'
            - '@App\Security\SecurityLogger'
            - '@logger'

    # Secrets Management Services
    App\Service\SecretEncryptionService:
        arguments:
            $appSecret: '%env(APP_SECRET)%'
            $encryptionSalt: 'skybroker_secrets_v2'

    App\Service\SecretsManagerService:
        arguments:
            $secretRepository: '@App\Repository\SecretRepository'
            $auditLogRepository: '@App\Repository\SecretAuditLogRepository'
            $encryptionService: '@App\Service\SecretEncryptionService'
            $security: '@security.helper'
            $requestStack: '@request_stack'
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'secrets' }

    # InPost Services
    App\Domain\InPost\Service\InPostService:
        arguments:
            $environment: 'sandbox'
        tags:
            - { name: 'courier.service', alias: 'inpost' }
            
    App\Domain\InPost\Service\InPostShipmentService:
        arguments:
            - '@App\Service\InPostApiClient'
            - '@App\Repository\ShipmentRepository'
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
        tags:
            - { name: 'monolog.logger', channel: 'inpost' }